apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsvapp-dev

resources:
  - env.yaml
  - namespace.yaml

bases:
  - ../../module


images:
  - name: mongo
    newTag: "3.3"
    newName: mongo
  - name: nginx
    newTag: 1.21.6
    newName: nginx
  