apiVersion: v1
kind: Service
metadata:
  name: webserver-blue-svc
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    type: frontend
    service: webserver-blue-svc

---

apiVersion: v1
kind: Service
metadata:
  name: webserver-green-svc
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    type: frontend
    service: webserver_green_svc

---   

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: blue.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: webserver-blue-svc
            port:
              number: 80
  - host: green.example.com
    http:
      paths:
        - path: /v2
          pathType: Prefix
          backend:
            service:
              name: webserver-green-svc
              port: 
                number: 80



