version: '3'

volumes:
  product-db-data:

services:
  product:
    platform: linux/x86_64
    build:
      context: .
    ports:
      - 80:5000
    links:
      - product_db
    depends_on:
      - product_db

  product_db:
    platform: linux/x86_64
    image: mysql:5.7.37
    volumes:
      - product-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=product