---
- hosts: all
 
  vars:
    node_apps_location: /usr/local/opt/node

  roles:
    - pre_tasks
    - nodejs

  tasks:
    - name: Ensure Node.js app folder exists.
      become: true
      become_method: sudo
      file: "path={{ node_apps_location }} state=directory"

    - name: Copy example Node.js app to server.
      copy: "src=app dest={{ node_apps_location }}"

    - name: Install app dependencies defined in package.json.
      npm: "path={{ node_apps_location }}/app"

    - name: Check list of running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false
      ignore_errors: true

    - name: Start example Node.js app.
      command: "forever start {{ node_apps_location }}/app/app.js"
      # when: "forever_list.stdout.find(node_apps_location + '/app/app.js') == -1"
