apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rsvapp-prod

resources:
  - env.yaml
  - namespace.yaml

bases:
  - ../../module

images:
  - name: mongo
    newTag: "3.4"
    newName: mongo
  - name: nginx
    newTag: latest
    newName: nginx
  